author      : Ramnath Vaidyanathan
job         : McGill University
logo        : slidify_logo.png
biglogo     : slidify_logo.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : solarized_light      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained
url         : {lib: "../../libraries"}
