---
title       : How it Works
subtitle    : rCharts
---

```{r setup, echo = F, message = F, cache = F}
knitr::opts_chunk$set(tidy = F, message = F, comment = NA, results = 'asis')
include <- function(file){
  writeLines(paste('    ', readLines(file)))
}
options(RCHART_WIDTH = 900, RCHART_HEIGHT = 400)
library(xtable)
options(xtable.type = 'html', xtable.include.rownames = F)
```

<iframe src="http://jsfiddle.net/RR8Ub/embedded/result,resources,js,html/presentation/" height=600 width=100%></iframe>

---

<iframe src="http://jsfiddle.net/RR8Ub/embedded/resources/presentation/" height=600 width=100%></iframe>

---

## Resources => Configuration (config.yml)

```yaml
uvcharts:
  jshead: [js/d3.v3.min.js, js/uvcharts.js]
  cdn:
    jshead:
      - "http://cdnjs.cloudflare.com/ajax/libs/d3/3.2.2/d3.v3.min.js"
      - "http://imaginea.github.io/uvCharts/js/uvcharts.js"
```

---

<iframe src="http://jsfiddle.net/RR8Ub/embedded/js/presentation/" height=600 width=100%></iframe>

--- .RAW

## Javascript => Layout (layouts/chart.html)

```js
<script>
  var graphdef = {{{ chartParams }}}
  var config = {
    meta: {
      position: "#{{ chartId }}"
    }
  }
  var chart = uv.chart(graphdef.type, graphdef, config)
</script>
```

---

## Data

```{r echo = F, results = 'asis'}
hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")
xtable(head(hair_eye_male, 10))
```

---

## JSON

```js
"dataset": {
  "Brown": [
    {"name": "Black", "value": 32 },
    {"name": "Brown", "value": 53 },
    {"name": "Red","value":  10},
    {"name": "Blond", "value": 3} 
  ],
  "Blue": [
    {"name": "Black", "value": 11 },
    {"name": "Brown", "value": 50 },
    {"name": "Red","value":  10},
    {"name": "Blond", "value": 30} 
  ],
  ...
} 
```

---

## Data => JSON

```{r}
make_dataset <- function(x, y, data, group = NULL){
  require(plyr)
  dat <- rename(data, setNames(c('name', 'value'), c(x, y)))
  dat <- dat[c('name', 'value', group)]
  if (!is.null(group)){
    dlply(dat, group, toJSONArray, json = F)
  } else {
    list(main = toJSONArray(dat, json = F)) 
  }
}
```

---

## Make Chart

```{r results = 'hide'}
dataset = make_dataset('Hair', 'Freq', hair_eye_male, group = 'Eye')
u1 <- rCharts$new()
u1$setLib("uvcharts")
u1$set(
  type = 'Bar',
  categories = names(dataset),
  dataset = dataset,
  dom = 'chart1'
)
u1
```

---

```{r chart1, echo = F}
u1
```

---

## Wrapper Function

```{r}
uvPlot <- function(x, y, data, group = NULL, type, ...){
  dataset = make_dataset(x = x, y = y, data = data, group = group)
  u1 <- rCharts$new()
  u1$setLib("uvcharts")
  u1$set(
    type = type,
    categories = names(dataset),
    dataset = dataset
  )
  return(u1)
}
```

---

## Links

1. [How it Works: Part 1](http://rcharts.io/howitworks)
2. [How it Works: Part 2](http://rcharts.io/howitworks/part2/)
2. [How it Works: Micropolar](http://rcharts.io/howitworks/micropolar)














